settings:
  island_distance: 1000
  island_world: "skyblock"
  protected_blocks:
    - "chest"
    - "furnace"
    - "hopper"

quests:
  "Wood Collector":
    description: "Collect 64 oak logs"
    objective:
      type: "block_break"
      block: "oak_log"
      amount: 64
    reward:
      xp: 100
    cooldown: 86400

leveling:
  xp_per_level: 1000
