name: GZSkyblock
main: SkyblockCore\Main
api: 5.0.0
version: 1.0.0
author: YourName
commands:
  island:
    description: Manage your skyblock island
    usage: "/island [create|teleport|info]"
    permission: "skyblock.command.island"  # Add this line
  balance:
    description: Check your balance
    usage: "/balance"
    permission: "skyblock.command.balance"  # Add this line
permissions:
  skyblock.command.island:
    description: Allows use of island commands
    default: true
  skyblock.command.balance:
    description: Allows checking balance
    default: true
depend:
  - EconomyAPI
